version: '3'
services:
  webapp:
    image: rust-webapp
    container_name: rust-webapp-container
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - PORT=3000
      - HOST=0.0.0.0
    restart: unless-stopped
